#!/usr/bin/env bash

BASE_DIR=/autograder/autograder_samples

# Update autograder files
cd /autograder/autograder_samples
git pull

cp /autograder/submission_metadata.json $BASE_DIR/submission_metadata.json

# Copy Google service account key
cp /autograder/source/secret.json /autograder/autograder_samples/secret.json

pip install -r $BASE_DIR/requirements.txt

cd $BASE_DIR

python3 run_tests.py